// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SamirBoulema.TGit
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidImagesString = "fec49b6d-c04a-42bd-b021-b8b2e5cfb291";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string HTMLContextString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public static Guid HTMLContext = new Guid(HTMLContextString);

        public const string CSSContextString = "64da400e-b4ad-4d67-aa92-4b7acb01ecd5";
        public static Guid CSSContext = new Guid(CSSContextString);

        public const string ASPXContextString = "d7e8c5e1-bdb8-11d0-9c88-0000f8040a53";
        public static Guid ASPXContext = new Guid(ASPXContextString);

        public const string guidTGitPkgString = "6c58d6e5-11ba-43ba-9a63-a624f264ec06";
        public static Guid guidTGitPkg = new Guid(guidTGitPkgString);

        public const string guidTGitCmdSetString = "6a672d8c-b58f-4329-9bc9-015fc15f9d1a";
        public static Guid guidTGitCmdSet = new Guid(guidTGitCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int showChangesImage = 0x0001;
        public const int pullImage = 0x0002;
        public const int pushImage = 0x0003;
        public const int showLogImage = 0x0004;
        public const int revertImage = 0x0005;
        public const int branchImage = 0x0006;
        public const int mergeImage = 0x0007;
        public const int differences = 0x0008;
        public const int blame = 0x0009;
        public const int repo = 0x000A;
        public const int resolveImage = 0x000B;
        public const int syncImage = 0x000C;
        public const int commitImage = 0x000D;
        public const int disk = 0x000E;
        public const int switchImage = 0x000F;
        public const int cleanupImage = 0x0010;
        public const int stash = 0x0011;
        public const int fetchImage = 0x0012;
        public const int browseRefImage = 0x0013;
        public const int tagImage = 0x0014;
        public const int abortMergeImage = 0x0015;
        public const int rebaseImage = 0x0016;
        public const int revgraph = 0x0017;
        public const int config = 0x0018;
        public const int add = 0x0019;
        public const int HTMLContextMenu = 0x0001;
        public const int CSSContextMenu = 0x0002;
        public const int ASPXContextMenu = 0x0035;
        public const int TGitMenu = 0x1021;
        public const int firstMenuGroup = 0x1020;
        public const int secondMenuGroup = 0x1022;
        public const int thirdMenuGroup = 0x1023;
        public const int fourthMenuGroup = 0x1024;
        public const int fifthMenuGroup = 0x1025;
        public const int sixthMenuGroup = 0x1026;
        public const int TGitSVNMenu = 0x4000;
        public const int TGitSVNMenuGroup = 0x4001;
        public const int svnDCommit = 0x0143;
        public const int svnRebase = 0x0144;
        public const int svnFetch = 0x0145;
        public const int TGitGitFlowMenu = 0x2000;
        public const int TGitGitFlowMenuGroup = 0x2001;
        public const int startFeature = 0x0100;
        public const int finishFeature = 0x0101;
        public const int startRelease = 0x0133;
        public const int finishRelease = 0x0134;
        public const int startHotfix = 0x0135;
        public const int finishHotfix = 0x0136;
        public const int init = 0x0139;
        public const int TGitGitHubFlowMenu = 0x3000;
        public const int TGitGitHubFlowMenuGroup = 0x3001;
        public const int startFeatureGitHub = 0x3002;
        public const int finishFeatureGitHub = 0x3003;
        public const int TGitContextMenu = 0x1027;
        public const int contextMenuGroup = 0x1028;
        public const int firstContextMenuGroup = 0x1029;
        public const int secondContextMenuGroup = 0x1030;
        public const int thirdContextMenuGroup = 0x1031;
        public const int fourthContextMenuGroup = 0x1032;
        public const int Toolbar = 0x1000;
        public const int ToolbarGroup = 0x1050;
        public const int showChanges = 0x0103;
        public const int pull = 0x0104;
        public const int fetch = 0x0127;
        public const int commit = 0x0105;
        public const int push = 0x0106;
        public const int showLog = 0x0107;
        public const int diskBrowser = 0x0108;
        public const int repoBrowser = 0x0109;
        public const int revGraph = 0x0148;
        public const int createStash = 0x0110;
        public const int applyStash = 0x0111;
        public const int stashPop = 0x0149;
        public const int branch = 0x0112;
        public const int switchBranch = 0x0113;
        public const int merge = 0x0114;
        public const int revert = 0x0115;
        public const int cleanup = 0x0116;
        public const int resolve = 0x0137;
        public const int sync = 0x0138;
        public const int browseRef = 0x0140;
        public const int showLogContext = 0x0117;
        public const int diskBrowserContext = 0x0118;
        public const int repoBrowserContext = 0x0119;
        public const int revGraphContext = 0x0147;
        public const int blameContext = 0x0120;
        public const int mergeContext = 0x0121;
        public const int pullContext = 0x0122;
        public const int fetchContext = 0x0128;
        public const int commitContext = 0x0123;
        public const int revertContext = 0x0124;
        public const int diffContext = 0x0125;
        public const int prefDiffContext = 0x0126;
        public const int tag = 0x0141;
        public const int abortMerge = 0x0142;
        public const int rebase = 0x0146;
        public const int addContext = 0x0150;
        public const int deleteContext = 0x0151;
        public const int deleteKeepContext = 0x0152;
    }
}